import Head from 'next/head'
import HomeCounter from '../components/homeCounter'

export default function Home() {
  return (
    <div className='bg-humo bg-cover bg-fixed bg-center w-screen h-screen'>
      <Head>
        <title>FinalFest 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/party.ico" />
      </Head>
      <main className='flex flex-col h-screen '>
        <HomeCounter />
      </main>
    </div>
  )
}
